### ISSUE TITLE
加载错误的网络视频，app卡死 

### ISSUE THREAD

**Issue by mrTangYun** [qq326646683/flutter_tencentplayer#109]
### 1. 设备/系统版本:
flutter:2.2.0,  flutter_tencentplayer: 1.1.0
### 2. bug描述:
加载播放一个失效的网络视频文件，比如：https://aweme.snssdk.com/aweme/v1/play/?video_id=v0200f3b0000bn5vpnigd9fk4atai8jg&line=0&ratio=540p&watermark=1&media_type=4&vr_type=0&improve_bitrate=0&logo_name=aweme

### 3. 实际结果:
安卓app卡死, 
### 5. 代码说明:
```
TencentPlayerController.network(
              'https://aweme.snssdk.com/aweme/v1/play/?video_id=v0200f3b0000bn5vpnigd9fk4atai8jg&line=0&ratio=540p&watermark=1&media_type=4&vr_type=0&improve_bitrate=0&logo_name=aweme',
              playerConfig: PlayerConfig(loop: true))
            ..initialize()
```

**Comment by qq326646683** [comment]
在ui线程读取无效链接导致的，已经在1.2.0修复
