### ISSUE TITLE
Key url expected String but value was a java.lang.Integer.  The default value <null> was returned.

### ISSUE THREAD

**Issue by liuys635** [qq326646683/flutter_tencentplayer#110]
W/Bundle  (11069): Key url expected String but value was a java.lang.Integer.  The default value <null> was returned.
W/Bundle  (11069): Attempt to cast generated internal exception:
W/Bundle  (11069): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
W/Bundle  (11069): 	at android.os.BaseBundle.getString(BaseBundle.java:1167)
W/Bundle  (11069): 	at com.tencent.liteav.txcvodplayer.TXCVodVideoView$5.onNativeInvoke(TXCVodVideoView.java:759)
W/Bundle  (11069): 	at com.tencent.ijk.media.player.IjkMediaPlayer.onNativeInvoke(IjkMediaPlayer.java:1219)

**Comment by qq326646683** [comment]
看报错，应该是传值类型错了，参考example里的事例代码，再不行把代码贴一下

**Comment by qq326646683** [comment]
播放的url为无效播放地址时会报这个错误，ui上可以根据errorInfo或者eventCode提示用户“资源出错，播放错误”
