### ISSUE TITLE
你好,这个播放器如何主动的去控制音量和屏幕亮度?

### ISSUE THREAD

**Issue by judastatus** [qq326646683/flutter_tencentplayer#114]

**Comment by qq326646683** [comment]
需要借助其他插件来控制，可以参考example

**Comment by judastatus** [comment]
> 需要借助其他插件来控制，可以参考example

好的,谢谢,我去看下最新的example
背景需求是:播放器手势支持上下拖动来调节亮度,当退出页面时候,亮度没有恢复为默认值,所以才有此issue.
