### ISSUE TITLE
请问是否可以支持播放rtmp？

### ISSUE THREAD

**Issue by shulw** [qq326646683/flutter_tencentplayer#15]

**Comment by qq326646683** [comment]
试了一下，android可以，ios腾讯sdk会报一个错误。已经放到example里了可以试一下

**Comment by shulw** [comment]
@qq326646683  好的，已验证，ios的播放问题能修复吗？

**Comment by qq326646683** [comment]
向官方提了issue，可以跟进
https://github.com/tencentyun/SuperPlayer_iOS/issues/139

**Comment by oreo** [comment]
我也遇到同样的问题

**Comment by oreo** [comment]
The file “hunantv” couldn’t be opened because there is no such file.
