### ISSUE TITLE
不支持 androidx吗？ 为什么运行demo 会报错呢 ? 

### ISSUE THREAD

**Issue by seeyou888999** [qq326646683/flutter_tencentplayer#16]
INFO: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.
Affected Modules: app, flutter_forbidshot, flutter_tencentplayer_plus, path_provider, path_provider_macos, screen

蛮多错误的。

**Comment by qq326646683** [comment]
是刚拉的代码吗，我刚刚跑是正常的，你把android.enableR8这行去掉试一试呢

**Comment by seeyou888999** [comment]
跑是跑起来了，但是代码好像不支持x86，只支持arm。改过了也一样。 在模拟器上会闪退。？难道
![fc490cfdee27e52fd11ccf735898276](https://user-images.githubusercontent.com/50047667/76177705-10cae880-61f0-11ea-90ab-c1d4957d5df6.png) 这两个文件只支持 arm 不支持x86么？ 没有安卓机。笔记本不是mac  又点小尴尬。。。

**Comment by qq326646683** [comment]
我用真机是ok的，模拟器应该要支持arm才可以，可以参考下这篇文章介绍怎么把模拟器支持arm：https://blog.csdn.net/Leafage_M/article/details/86675699
