### ISSUE TITLE
关于m3u8地址定向的问题

### ISSUE THREAD

**Issue by bombp** [qq326646683/flutter_tencentplayer#18]
功能还是非常好用的。但目前只能下载包含了ts文件的m3u8地址，对于需要重定向的地址不支持如"https://v2.438vip.com/20170918/YCBDXfYz/index.m3u8"内容如下：
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1000000,RESOLUTION=1024x576
1000kb/hls/index.m3u8
```
可以考虑完善一下。

**Comment by qq326646683** [comment]
你好，关于支持播放重定向m3u8你可以去腾讯官方库提issue跟进一下：https://github.com/tencentyun/SuperPlayer_iOS
