### ISSUE TITLE
Adaptive HLS

### ISSUE THREAD

**Issue by Michael24884** [qq326646683/flutter_tencentplayer#21]
According to the docs on the TencentPlayer SDK it was noted that the player supported adaptive streaming but while testing the Flutter TencentPlayer the video only plays one stream and does not adapt.

**Comment by qq326646683** [comment]
I have n’t tried adapter hls yet, please provide a log that ca n’t be played, or play a link to let me try

**Comment by Michael24884** [comment]
Sure, here’s a test link : https://edge.flowplayer.org/playful.m3u8

This supports qualities from 240p to 1080p but TencentPlayer always chooses 240p and doesn’t update the qualities
