### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by q200892907** [qq326646683/flutter_tencentplayer#22]
进行 flutter build apk后  安装真机出现崩溃问题

#19 相同的错误

**Comment by lylelqc** [comment]
是和混淆有关？我打正式包也crash

**Comment by qq326646683** [comment]
@q200892907 @lylelqc 用readme最下面note命令打包看看

**Comment by lylelqc** [comment]
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.
     Required by:
         project :app
      > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c6689
92d2e9da761118899f38.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c668992d2e9
da761118899f38.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.80] failed: Connection timed out: connect
      > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c6689
92d2e9da761118899f38.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c668992d2e9
da761118899f38.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.80] failed: Connection timed out: connect
      > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c6689
92d2e9da761118899f38.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c668992d2e9
da761118899f38.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.80] failed: Connection timed out: connect


是没有合理上网吗 @qq326646683

**Comment by qq326646683** [comment]
@lylelqc 看上去是的，我没遇到过，之前也没人向我反馈过

**Comment by qq326646683** [comment]
@lylelqc 确认翻q后，在终端也启动下就行：
export http_proxy=http://127.0.0.1:1087
export https_proxy=http://127.0.0.1:1087
测试
curl www.google.com

**Comment by lylelqc** [comment]
用的windows系统，有点懵。。

**Comment by lylelqc** [comment]
> @lylelqc 确认翻q后，在终端也启动下就行：
> export http_proxy=http://127.0.0.1:1087
> export https_proxy=http://127.0.0.1:1087
> 测试
> curl [www.google.com](http://www.google.com)

用的windows系统，有点懵
