### ISSUE TITLE
安卓中模拟器闪退

### ISSUE THREAD

**Issue by lhh-sofy** [qq326646683/flutter_tencentplayer#24]
你好，在安卓模拟器中，打开网络视频时，直接闪退，只要打开视频就闪退了
1.mac系统    2.跑当是你当git中当示例
当打开一个视频时候， 报错如下：

> D/EGL_emulation(26772): eglMakeCurrent: 0xf1380e20: ver 3 0 (tinfo 0xc11d6ae0)
D/EGL_emulation(26772): eglMakeCurrent: 0xe5fe8a40: ver 3 0 (tinfo 0xe60c8a00)
D/EGL_emulation(26772): eglMakeCurrent: 0xf1380e20: ver 3 0 (tinfo 0xc11d6ae0)
W/Native-LiteAV(26772): load library txffmpeg from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtxffmpeg.so"
W/Native-LiteAV(26772): load library txffmpeg false
W/Native-LiteAV(26772): load library traeimp-rtmp from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtraeimp-rtmp.so"
W/Native-LiteAV(26772): load library traeimp-rtmp false
W/Native-LiteAV(26772): load library liteavsdk from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libliteavsdk.so"
W/Native-LiteAV(26772): load library liteavsdk false
W/Native-LiteAV(26772): load library txffmpeg from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtxffmpeg.so"
W/Native-LiteAV(26772): load library txffmpeg false
W/Native-LiteAV(26772): load library traeimp-rtmp from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtraeimp-rtmp.so"
W/Native-LiteAV(26772): load library traeimp-rtmp false
W/Native-LiteAV(26772): load library liteavsdk from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libliteavsdk.so"
W/Native-LiteAV(26772): load library liteavsdk false
W/Native-LiteAV(26772): load library txffmpeg from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtxffmpeg.so"
W/Native-LiteAV(26772): load library txffmpeg false
W/Native-LiteAV(26772): load library traeimp-rtmp from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libtraeimp-rtmp.so"
W/Native-LiteAV(26772): load library traeimp-rtmp false
W/Native-LiteAV(26772): load library liteavsdk from system path
W/Native-LiteAV(26772): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86, /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libliteavsdk.so"
W/Native-LiteAV(26772): load library liteavsdk false
E/tplayer_exampl(26772): No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
E/flutter (26772): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
E/flutter (26772): 	at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
E/flutter (26772): 	at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:393)
E/flutter (26772): 	at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:372)
E/flutter (26772): 	at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:183)
E/flutter (26772): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.setPlaySource(FlutterTencentplayerPlugin.java:193)
E/flutter (26772): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.<init>(FlutterTencentplayerPlugin.java:82)
E/flutter (26772): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin.onMethodCall(FlutterTencentplayerPlugin.java:473)
E/flutter (26772): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/flutter (26772): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (26772): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/flutter (26772): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26772): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (26772): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (26772): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (26772): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26772): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (26772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (26772):
F/flutter (26772): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
F/libc    (26772): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26772 (tplayer_example), pid 26772 (tplayer_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-05-11 13:10:59+0800
pid: 26772, tid: 26772, name: tplayer_example  >>> com.jinxian.flutter_tencentplayer_example <<<
uid: 10146
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
'
    eax 00000000  ebx 00006894  ecx 00006894  edx 00000006
    edi ee98933e  esi ffeb9520
    ebp f168cad0  esp ffeb94c8  eip f168cad9
backtrace:
      #00 pc 00000ad9  [vdso] (__kernel_vsyscall+9)
      #01 pc 00092328  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #02 pc 000ad651  /apex/com.android.runtime/lib/bionic/libc.so (abort+193) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #03 pc 0113d6e2  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #04 pc 01129ef5  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #05 pc 0112799e  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #06 pc 01194473  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #07 pc 0113baf3  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #08 pc 0113e437  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #09 pc 0113e37a  /data/app/com.jinxian.flutter_tencentplayer_example-ZbCFKblyxaD83aTz_SSZwA==/lib/x86/libflutter.so (BuildId: 882b627e1004b36ce49b72e29210757a9ba6ced5)
      #10 pc 0008d8bf  [anon:libc_malloc]
Lost connection to device.
Exited (sigterm)

**Comment by qq326646683** [comment]
用真机试吧，模拟器我还没试过，应该不支持
