### ISSUE TITLE
报错！！！

### ISSUE THREAD

**Issue by songguowei** [qq326646683/flutter_tencentplayer#25]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_tencentplayer:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_tencentplayer:debugCompileClasspath'.
   > Could not find :LiteAVSDK_Player:.
     Required by:
         project :flutter_tencentplayer
   > Could not find :libsuperplayer:.
     Required by:
         project :flutter_tencentplayer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by qq326646683** [comment]
看上去没有找到aar，你有配置1.setup for android部分吗

**Comment by songguowei** [comment]
> 看起来没有找到aar，你有配置1.setup for android部分吗

我跑你的demo也跑不起来！

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
         project :app > project :flutter_forbidshot
         project :app > project :screen
         project :app > project :path_provider
         project :app > project :flutter_tencentplayer
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/flutter_embedding_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
            > Could not HEAD 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/flutter_embedding_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.112] failed: Read timed out
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/arm64_v8a_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
            > Could not HEAD 'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/arm64_v8a_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.112] failed: Read timed out
   > Could not resolve io.flutter:x86_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/x86_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
            > Could not HEAD 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/x86_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.112] failed: Read timed out
   > Could not resolve io.flutter:x86_64_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/x86_64_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
            > Could not HEAD 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/x86_64_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.112] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by qq326646683** [comment]
网络问题哦
