### ISSUE TITLE
关于iOS端设置progressInterval参数无效的问题

### ISSUE THREAD

**Issue by tuchengdong** [qq326646683/flutter_tencentplayer#26]
你好~非常感谢你封装的播放器,给我带来很大的便利,谢谢~然后我在使用的过程中发现,iOS端 在设置progressInterval 参数后 没有效果, 不知是否可以帮忙查看下~谢谢

**Comment by yxwandroid** [comment]
![image](https://user-images.githubusercontent.com/9635493/81799590-21774200-9544-11ea-8260-014f33b5ecac.png)
ios端是写死了  你可以fork 下来然后改一下就行

@tuchengdong

**Comment by qq326646683** [comment]
@yxwandroid 要不你改下，发个pull request，或者告诉我怎么改

**Comment by qq326646683** [comment]
@tuchengdong 你好，已经在0.5.0版本修复，可以尝试

**Comment by tuchengdong** [comment]
好的 谢谢~
