### ISSUE TITLE
Https link with  m3u8 not supported for download

### ISSUE THREAD

**Issue by MeTubeapp** [qq326646683/flutter_tencentplayer#27]
Hello sir, your package is awesome but sir there is a problem with https link .if m3u8 link with https it is not support for downloads why please sir help me...thanks in advance

**Comment by qq326646683** [comment]
hi，Are you using Tencent's video source？this plugin is only suitable for downloading Tencent's

**Comment by MeTubeapp** [comment]
ok sir thanks for reply
