### ISSUE TITLE
怎么监听是否播放完毕呢

### ISSUE THREAD

**Issue by songguowei** [qq326646683/flutter_tencentplayer#30]

**Comment by qq326646683** [comment]
![image](https://user-images.githubusercontent.com/15717688/82788422-05a46200-9e9b-11ea-995c-ae1008b8b1e5.png)
监听判断position==duration即播放完成

**Comment by songguowei** [comment]
> ![image](https://user-images.githubusercontent.com/15717688/82788422-05a46200-9e9b-11ea-995c-ae1008b8b1e5.png)
> 监听判断position==duration即播放完成

这个监听代码写在哪里呢

**Comment by qq326646683** [comment]
addListener里
