### ISSUE TITLE
想问一下关于 填充模式这边铺满是怎么做

### ISSUE THREAD

**Issue by 309791679** [qq326646683/flutter_tencentplayer#32]
AspectRatio
比例来搞,会有黑边最小0.9

我做了一个定制高度组件比例是横屏占左边一半,
但是我想让视频铺满,没有看到关于填充模式的api,想请问一下应该怎么做

**Comment by 309791679** [comment]
![image](https://user-images.githubusercontent.com/26238458/83937694-a2eb8880-a801-11ea-934d-ee7aed00021a.png)

循环播放,第二个播放完成后会卡屏,是要做什么特别处理吗还是我写的不对,我没有看到文档中有写关于这个方面的东西

**Comment by qq326646683** [comment]
循环播放可以设置playconfig的loop属性

**Comment by qq326646683** [comment]
铺满屏幕可以用dart端用flutter ui实现，可以研究一下

**Comment by 309791679** [comment]
我说的循环是 每次结束后

> 铺满屏幕可以用dart端用flutter ui实现，可以研究一下

我说的循环是每次结束后切换下一个视频播放,而这个就回出现,第二个视频播放完成就卡顿的情况,好像是什么地方的状态没有刷新

**Comment by qq326646683** [comment]
切换视频源可以参考demo里的写法

**Comment by qq326646683** [comment]
播放结束可以监听position==duration

**Comment by 309791679** [comment]
这个问题是解决了
但是播放大约10个视频后就会奔溃了

![360截图20200606145808509](https://user-images.githubusercontent.com/26238458/83938374-2e671880-a806-11ea-81b9-02e5c39b4be3.jpg)

**Comment by 309791679** [comment]
我现在去除了其他的

> 切换视频源可以参考demo里的写法

我去除了其他的代码,还是会出现奔溃

**Comment by 309791679** [comment]
> 切换视频源可以参考demo里的写法

  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight
    ]);
    ScreenUtil.init(context, width: 414, height: 736, allowFontScaling: true);
       return Scaffold(
        body: Row(
          children: <Widget>[
            SizedBox(
              height: ScreenUtil().setHeight(736),
              width: ScreenUtil().setWidth(220),
              child: GestureDetector(
                onDoubleTap: () {
                  if (controller.value.isPlaying) {
                    controller.pause();
                  } else {
                    controller.play();
                  }
                },
                child: Container(
                  color: Colors.black,
                  child: Stack(
                    overflow: Overflow.visible,
                    alignment: Alignment.center,
                    children: <Widget>[

                      /// 视频
                      AspectRatio(aspectRatio: 0.95,
                        child: TencentPlayer(controller),
                      )
                    ],
                  ),


                ),
              ),
            ),

          ],
        ),
      );


  }


这是我的代码, 我对flutter 不太熟悉,所以不确定是不是调用初始化次数过多导致,内存泄漏

**Comment by qq326646683** [comment]
最近有些忙，有时间我把铺满功能加到example里

**Comment by 309791679** [comment]
> 最近有些忙，有时间我把铺满功能加到example里

嗯,好的,关于上面我说的多次调用初始化会导致内存泄漏\崩溃的情况,还需要麻烦你那边看看,我这边测试确实是这样,使用本地文件
