### ISSUE TITLE
一直在launching 无法下载

### ISSUE THREAD

**Issue by zhanglijie5997** [qq326646683/flutter_tencentplayer#33]
![image](https://user-images.githubusercontent.com/42401363/83937653-60c24700-a801-11ea-9142-482ca109f6af.png)

**Comment by qq326646683** [comment]
下载什么🤔截图没看懂…

**Comment by zhanglijie5997** [comment]
一直在启动模拟器，无法打开模拟器，跑不起来😅，依赖也没安装下来，科学上网也不行...

**Comment by qq326646683** [comment]
加好友已解决，得知是ios签名问题

**Comment by bravolover520** [comment]
me too

**Comment by zhanglijie5997** [comment]
> me too

cd ios目录，pod install，安卓用as打开，进入安卓目录，等他build完解决
