### ISSUE TITLE
多次调用初始化会导致奔溃

### ISSUE THREAD

**Issue by 309791679** [qq326646683/flutter_tencentplayer#34]
TencentPlayerController controller;
  VoidCallback listener;

  bool isLock = false;
  bool showCover = false;
  Timer timer;

  @override
  void initState() {
    super.initState();
    _initController();
    controller.addListener(listener);
    Screen.keepOn(true);
    csc();
  }

  @override
  Future dispose() {
    super.dispose();
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top, SystemUiOverlay.bottom]);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    controller.removeListener(listener);
    if (widget.controller == null) {
      controller.dispose();
    }
    ForbidShotUtil.disposeForbid();
    Screen.keepOn(false);
  }

  Future csc() async {
    if (await Permission.contacts.request().isGranted) {}
    Map<Permission, PermissionStatus> statuses = await [
      Permission.location,
      Permission.storage,
    ].request();
  }

  _initController() {
    if (widget.controller != null) {
      controller = widget.controller;
      return;
    }
    controller = TencentPlayerController.file(widget.dataSource);
    controller.initialize();
        Timer.periodic(Duration(seconds: 1), (time) {
          if (controller.value.isPlaying==false) {
            controller.removeListener(listener);
            controller = TencentPlayerController.file('/storage/emulated/0/test.mp4');
            controller.initialize().then((_) {
              setState(() {});
            });
            controller.addListener(listener);
            Screen.keepOn(true);
          }
    });
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight
    ]);
    ScreenUtil.init(context, width: 414, height: 736, allowFontScaling: true);
       return Scaffold(
        body: Row(
          children: <Widget>[
            SizedBox(
              height: ScreenUtil().setHeight(736),
              width: ScreenUtil().setWidth(220),
              child: GestureDetector(
                onDoubleTap: () {
                  if (controller.value.isPlaying) {
                    controller.pause();
                  } else {
                    controller.play();
                  }
                },
                child: Container(
                  color: Colors.black,
                  child: Stack(
                    overflow: Overflow.visible,
                    alignment: Alignment.center,
                    children: <Widget>[
                      AspectRatio(aspectRatio: 0.95,
                        child: TencentPlayer(controller),
                      )
                    ],
                  ),
                ),
              ),
            ),

            SizedBox(
              height: ScreenUtil().setHeight(736),
              width: ScreenUtil().setWidth(194),
              child: Swiper(
                itemBuilder: (BuildContext context, int index) {
                  return new Image.network(
                    "http://via.placeholder.com/350x150",
                    fit: BoxFit.fill,
                  );
                },
                itemCount: 3,
                autoplay: true,
              ),
            )
          ],
        ),
      );

  }

}

主要功能就是,循环播放本地的视频文件,会有不同的视频文件被播放,但是测试下来,超过30次播放就会奔溃

**Comment by 309791679** [comment]
使用官方案例

controller.removeListener(listener);
            controller.pause();
            controller = TencentPlayerController.file('/storage/emulated/0/test.mp4');
            controller.initialize().then((_) {
              if (mounted) setState(() {});
            });
            controller?.addListener(listener);



在运行15之后很明显感觉整体卡顿上升,之后崩溃

**Comment by qq326646683** [comment]
我最近有点忙，有时间我把循环列表播放放到example里
