### ISSUE TITLE
项目中集成不了插件

### ISSUE THREAD

**Issue by JackWu0312** [qq326646683/flutter_tencentplayer#38]

**Comment by JackWu0312** [comment]
Undefined symbols for architecture arm64:
      "_avDenoiseDoDenoise", referenced from:
          _LITEAV_DeNoise_Process in TXLiteAVSDK_Player(denoise_lstm.o)
      "_initializeXNN", referenced from:
          _LITEAV_DeNoise_Init in TXLiteAVSDK_Player(denoise_lstm.o)
      "_avDenoiseCreateHandle", referenced from:
          _LITEAV_DeNoise_Init in TXLiteAVSDK_Player(denoise_lstm.o)
      "_avDenoiseInitialize", referenced from:
          _LITEAV_DeNoise_Init in TXLiteAVSDK_Player(denoise_lstm.o)
      "_avDenoiseClearCache", referenced from:
          _LITEAV_DeNoise_Creat in TXLiteAVSDK_Player(denoise_lstm.o)
          _LITEAV_DeNoise_Free in TXLiteAVSDK_Player(denoise_lstm.o)
          _LITEAV_DeNoise_Process in TXLiteAVSDK_Player(denoise_lstm.o)
      "_avDenoiseFreeHandle", referenced from:
          _LITEAV_DeNoise_Creat in TXLiteAVSDK_Player(denoise_lstm.o)
          _LITEAV_DeNoise_Free in TXLiteAVSDK_Player(denoise_lstm.o)
      "_uninitializeXNN", referenced from:
          _LITEAV_DeNoise_Creat in TXLiteAVSDK_Player(denoise_lstm.o)
          _LITEAV_DeNoise_Free in TXLiteAVSDK_Player(denoise_lstm.o)

**Comment by qq326646683** [comment]
pod install成功了吗

**Comment by JackWu0312** [comment]
pod install 成功的了

**Comment by qq326646683** [comment]
你创建一个新flutter项目，集成试试看呢

**Comment by JackWu0312** [comment]
删掉 set building->other linker flag-> -all_load.  就解决了 也是在网上搜的具体原因也不清楚 小白一枚😭😭
