### ISSUE TITLE
controller初始化资源问题

### ISSUE THREAD

**Issue by hanleiZoro** [qq326646683/flutter_tencentplayer#43]
当我初始页面是一个竖向小窗口播放器 -> 然后切换到大屏幕播放器-> 点击切换分辨率。返回前一个窗口。前一个窗口会进入暂停状态。demo中会如此，我在现实的项目中也遇到了。能麻烦帮忙看看么？

**Comment by qq326646683** [comment]
回到窗口播放，需要将controller回传过来，已经在demo里体现了
