### ISSUE TITLE
大佬，更新下sdk啊，腾讯那边ios支持rtmp了

### ISSUE THREAD

**Issue by oreo** [qq326646683/flutter_tencentplayer#44]

**Comment by qq326646683** [comment]
已更新，我试了demo里的rtmp从报错变成了加载中

**Comment by gingerJY** [comment]
@qq326646683 您好，请问现在ios还是不支持rtmp吗
![image](https://user-images.githubusercontent.com/23522394/165073489-79c7cfb1-8ae3-440a-bf8b-3a2248ce99c9.png)
