### ISSUE TITLE
引入之后，也配置安卓的配置了，项目无法运行

### ISSUE THREAD

**Issue by BedRockGx** [qq326646683/flutter_tencentplayer#46]
引入之后出现
D:\work\flutter\FireTiger\fireTiger\android\app\src\debug\AndroidManifest.xml:29:9-29 Error:
        Attribute application@label value=(��ֱ��) from AndroidManifest.xml:29:9-29
        is also present at [:LiteAVSDK_Player_7.4.9211:] AndroidManifest.xml:26:9-41 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:27:5-62:19 to override.

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(��ֱ��) from AndroidManifest.xml:29:9-29
        is also present at [:LiteAVSDK_Player_7.4.9211:] AndroidManifest.xml:26:9-41 value=(@string/app_name).
        Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:27:5-62:19 to override.

**Comment by qq326646683** [comment]
现在怎么样了，ok了吗

**Comment by GitTradWang** [comment]
tools:replace="android:label 替换下就好了
