### ISSUE TITLE
项目如果开启了混淆打包后会闪退

### ISSUE THREAD

**Issue by nowexhas** [qq326646683/flutter_tencentplayer#48]
1、项目如果开启了混淆打包后会闪退，应该是需要混淆排除规则，请问这个怎么写？

2、取消下载后，提示是删除了下载任务，下载的文件并没删除，DEMO可以给个同时删除文件的例子吗？

感谢～～

**Comment by qq326646683** [comment]
1.我们flutter项目没有混淆，感觉没有混淆的必要。你用flutter build apk --release --no-shrink直接打包吧
2.取消下载任务后，可以用dart的删除文件处理一下。
