### ISSUE TITLE
可不可以支持一下签名播放、加密下载、解密播放这些功能呀

### ISSUE THREAD

**Issue by xlizy** [qq326646683/flutter_tencentplayer#52]

**Comment by qq326646683** [comment]
目前支持在线播放hls加密视频，通过playerconfig的headers参数去访问解密接口。下载只能下载并播放未加密的视频，腾讯sdk对播放下载的加密文件支持不稳定

**Comment by iwanglian** [comment]
playconfig的 auth里可以增加传 sign参数，这些签名是 业务后台根据腾讯云给的算法计算出来的

**Comment by qq326646683** [comment]
@iwanglian 嗯，playconfig里预留的有auth参数，没有用过，可以试试看
