### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by fcloud89** [qq326646683/flutter_tencentplayer#53]
pubspec.yaml文件中29-36行
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass

应该是 @qq326646683 你生成的吧，造成安卓和ios都无法引用这个插件了
应该改为
    androidPackage: com.jinxian.flutter_tencentplayer
    pluginClass: FlutterTencentplayerPlugin

@yxwandroid @qq326646683

**Comment by qq326646683** [comment]
谢谢提醒，0.9.0修复
