### ISSUE TITLE
安卓9.0系统视频播放崩溃

### ISSUE THREAD

**Issue by SnowWolf817** [qq326646683/flutter_tencentplayer#57]

**Comment by qq326646683** [comment]
有详细的日志吗

**Comment by SnowWolf817** [comment]
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.200819.001.A1/6823625:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-09-14 12:31:16+0800
pid: 5866, tid: 5866, name: .qifuyun.course  >>> com.qifuyun.course <<<
uid: 10151
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
'
    eax 00000000  ebx 000016ea  ecx 000016ea  edx 00000006
    edi e77bd80e  esi ffa80150
    ebp eb268b90  esp ffa800f8  eip eb268b99
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: a690ed60a8b6a282b41dd991389b5fdb)
      #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: a690ed60a8b6a282b41dd991389b5fdb)
      #03 pc 0117ef32  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #04 pc 0116b017  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #05 pc 0116613e  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #06 pc 011d5d33  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #07 pc 0117d1ed  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #08 pc 0117fd2b  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #09 pc 0117fc6e  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #10 pc 011860ce  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #11 pc 011860fc  /data/app/~~fO5mApchxcdpg5JPMfQVUQ==/com.qifuyun.course-dTqQIzWuBSE670HuhMQKRw==/lib/x86/libflutter.so (BuildId: 7fd5750d070fd5510c606bbac041c2ba81af8f5d)
      #12 pc 00019337  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #13 pc 0001a367  /system/lib/libutils.so (android::Looper::pollInner(int)+1127) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #14 pc 00019e96  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+118) (BuildId: ab4be013cda31e8c45d48aa23a89d0f8)
      #15 pc 0010ef8b  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59) (BuildId: 588f2cd5873ff4273bb25b25edb82606)
      #16 pc 0021be48  /system/framework/x86/boot-framework.oat (art_jni_trampoline+136) (BuildId: cd049c9ca9f46317ecd7d512d6b856181c4d6d60)
      #17 pc 02001ea6  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.MessageQueue.next+230)
      #18 pc 0013b922  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #19 pc 001d0381  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #20 pc 003866e1  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+385) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #21 pc 0037aa1e  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1070) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #22 pc 007a1197  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+967) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #23 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #24 pc 00396968  /system/framework/framework.jar (offset 0x92b000) (android.os.Looper.loop+156)
      #25 pc 0036fae2  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.12175385690420896393)+370) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #26 pc 00379bff  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+207) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #27 pc 0037b495  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+2117) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #28 pc 0018e613  /apex/com.android.art/lib/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+81395) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #29 pc 00142de2  /apex/com.android.art/lib/libart.so (ExecuteSwitchImplAsm+18) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #30 pc 001a1698  /system/framework/framework.jar (android.app.ActivityThread.main)
      #31 pc 0036fa6e  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.12175385690420896393)+254) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #32 pc 00379ae0  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+176) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #33 pc 0078b305  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+1061) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #34 pc 0014220d  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #35 pc 0013baf2  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #36 pc 001d0392  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+258) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #37 pc 0062ffe8  /apex/com.android.art/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1464) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #38 pc 00588680  /apex/com.android.art/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+80) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #39 pc 0008a778  /apex/com.android.art/javalib/x86/boot.oat (art_jni_trampoline+168) (BuildId: b386118502376442aa402e8d28c29e95a6eb8614)
      #40 pc 0013b922  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #41 pc 001d0381  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #42 pc 003866e1  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+385) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #43 pc 0037aa1e  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1070) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #44 pc 007a1197  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+967) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #45 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #46 pc 004492d2  /system/framework/framework.jar (offset 0x125d000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #47 pc 0036fae2  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.12175385690420896393)+370) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #48 pc 00379ae0  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+176) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #49 pc 0078b305  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+1061) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #50 pc 0014220d  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #51 pc 00893696  /system/framework/x86/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2102) (BuildId: cd049c9ca9f46317ecd7d512d6b856181c4d6d60)
      #52 pc 0013baf2  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #53 pc 001d0392  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+258) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #54 pc 0062e633  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, char*)+579) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #55 pc 0062eb05  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+85) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #56 pc 004ce62f  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+735) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #57 pc 003f8a8e  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+2846) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #58 pc 003e60b9  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+73) (BuildId: 123e60096a46399e6f56e4eb5c70759a)
      #59 pc 0008f90e  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+62) (BuildId: 588f2cd5873ff4273bb25b25edb82606)
      #60 pc 00098c8e  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+910) (BuildId: 588f2cd5873ff4273bb25b25edb82606)
      #61 pc 00003804  /system/bin/app_process32 (main+1588) (BuildId: c5eedbfb6130af84c3db8e121fb1202e)
      #62 pc 000522e3  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+115) (BuildId: a690ed60a8b6a282b41dd991389b5fdb)

**Comment by SnowWolf817** [comment]
> 有详细的日志吗

http://zhangliang0902.com/new/2019/03/21/flutter-video-player-bug-in-android9/
是不是跟这个错误是一样的？但是我试了你写的example还是一样崩溃

**Comment by qq326646683** [comment]
用的真机还是模拟器

**Comment by SnowWolf817** [comment]
> 用的真机还是模拟器

模拟器

**Comment by qq326646683** [comment]
请使用真机，不支持x86模拟器

**Comment by SnowWolf817** [comment]
> 请使用真机，不支持x86模拟器

昂~感谢回复
