### ISSUE TITLE
退出页面的时候，视频还播放着呢，使用你的官方例子的apk

### ISSUE THREAD

**Issue by abcd498936590** [qq326646683/flutter_tencentplayer#59]
两个情况
1：退出页面的时候，视频还播放着呢。有偶然的几率
2：视频全屏再切换到半屏的情况下，有的时候会闪，然后视频就看不到了

两个情况都是使用你自己提供的的那个apk

**Comment by qq326646683** [comment]
可以录个屏复现一下吗

**Comment by qq326646683** [comment]
试一下0.11.0的apk，如有bug，按照issue模版详细说明吧
