### ISSUE TITLE
运行报错-Xlint:unchecked 

### ISSUE THREAD

**Issue by MX8CLUB** [qq326646683/flutter_tencentplayer#60]
-Xlint:unchecked 

[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale zh-CN)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\***\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\***\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • G011C (mobile) • 127.0.0.1:21503 • android-x86 • Android 7.1.2 (API 25)

**Comment by qq326646683** [comment]
看上去不是插件的问题，百度“-Xlint:unchecked” 试试

**Comment by MX8CLUB** [comment]
> 
> 
> 看上去不是插件的问题，百度“-Xlint:unchecked” 试试

找过相关问题，没有解决，只要使用插件就会报错，去除就正常

**Comment by qq326646683** [comment]
能正常运行example吗

**Comment by MX8CLUB** [comment]
> 
> 
> 能正常运行example吗

刚拉下来跑了一下，也有报错

ע: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider-1.5.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\hzj19\Desktop\flutter_tencentplayer\android\src\main\java\com\jinxian\flutter_tencentplayer\FlutterTencentplayerPlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣

**Comment by MX8CLUB** [comment]
D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_tencentplayer-0.10.0\android\src\main\java\com\jinxian\flutter_tencentplayer\FlutterTencentplayerPlugin.java:117: ����: [unchecked] δ������ת��
                mPlayConfig.setHeaders((Map<String, String>) call.argument("headers"));
                                                                          ^
  ��Ҫ: Map<String,String>
  �ҵ�:    Object
D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_tencentplayer-0.10.0\android\src\main\java\com\jinxian\flutter_tencentplayer\FlutterTencentplayerPlugin.java:164: ����: [unchecked] δ������ת��
                Map authMap = (Map<String, Object>)call.argument("auth");
                                                                ^
  ��Ҫ: Map<String,Object>
  �ҵ�:    Object
2 ������

**Comment by MX8CLUB** [comment]
解决：必须使用真机调试，不能使用模拟器
