### ISSUE TITLE
iOS在列表播放时，部分视频加载不出来，播放停止混乱

### ISSUE THREAD

**Issue by iwanglian** [qq326646683/flutter_tencentplayer#61]
在ListView中使用player,  Android播放正常，但iOS播放混乱，一部分视频黑屏不能播放，一部分视频 .play()时播放别的视频

**Comment by iwanglian** [comment]
代码中看到 android是把多个player存到 map里；而iOS曾经也有这个map, 但后来注释掉，换成每次只使用最新的 player，是什么原因呢？
//    TencentVideoPlayer* player = _players[@(textureId)];

**Comment by qq326646683** [comment]
保证内存稳定前提下，修复了一版，你试试0.11.0能不能满足，对应抖音demo做的测试

**Comment by iwanglian** [comment]
强
