### ISSUE TITLE
视频播放结束后进度条会往回走了一下

### ISSUE THREAD

**Issue by Blues9527** [qq326646683/flutter_tencentplayer#62]
### 1. 设备/系统版本:
Android redmi note 7/ Android 9
### 2. bug描述:
利用controller.value.position监听当前播放进度，当播放结束后进度条往回走了一下
### 3. 实际结果:
视频播放结束当前进度与总进度不符
### 4. 预期结果:
视频播放结束时当前进度与总进度一致
### 5. 代码说明:
```
省略部分日志
`I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:09.960000, playable: 0:00:10.010000, isPlaying: true, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))
I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:09.976000, playable: 0:00:10.010000, isPlaying: true, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))
I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:09.994000, playable: 0:00:10.010000, isPlaying: true, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))
I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:10.010000, playable: 0:00:10.010000, isPlaying: true, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))
I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:09.594000, playable: 0:00:10.010000, isPlaying: false, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))
I/flutter ( 9211): 监听进度条： controller value ：TencentPlayerValue(duration: 0:00:10.010000, position: 0:00:09.594000, playable: 0:00:10.010000, isPlaying: false, errorDescription: null),isLoading: false),netSpeed: 0),rate: 1.0),bitrateIndex: 0),orientation: 0),degree: 0),size: Size(368.0, 640.0))`
```

**Comment by qq326646683** [comment]
我试了一下demo里的一分钟视频没有你说的情况，发我下你的视频源呢
```
I/flutter (10384): controller.value.position:0:01:00.569000
I/flutter (10384): controller.value.position:0:01:00.559000
I/flutter (10384): controller.value.position:0:01:00.602000
I/flutter (10384): controller.value.position:0:01:00.619000
I/flutter (10384): controller.value.position:0:01:00.635000
I/flutter (10384): controller.value.position:0:01:00.652000
I/flutter (10384): controller.value.position:0:01:00.669000
I/flutter (10384): controller.value.position:0:01:00.687000
I/flutter (10384): controller.value.position:0:01:00.702000
I/flutter (10384): controller.value.position:0:01:00.709000
I/flutter (10384): controller.value.position:0:01:00.727000
W/IJKMEDIA(10384): av_sync_type = AV_SYNC_VIDEO_MASTER 2
I/flutter (10384): controller.value.position:0:01:00.754000
I/flutter (10384): controller.value.position:0:01:00.772000
I/flutter (10384): controller.value.position:0:01:00.787000
I/flutter (10384): controller.value.position:0:01:00.805000
I/flutter (10384): controller.value.position:0:01:00.821000
I/flutter (10384): controller.value.position:0:01:00.838000
I/flutter (10384): controller.value.position:0:01:00.854000
I/flutter (10384): controller.value.position:0:01:00.698000
```

**Comment by Blues9527** [comment]
> 我试了一下demo里的一分钟视频没有你说的情况，发我下你的视频源呢
> 
> ```
> I/flutter (10384): controller.value.position:0:01:00.602000
> I/flutter (10384): controller.value.position:0:01:00.619000
> I/flutter (10384): controller.value.position:0:01:00.635000
> I/flutter (10384): controller.value.position:0:01:00.652000
> I/flutter (10384): controller.value.position:0:01:00.669000
> I/flutter (10384): controller.value.position:0:01:00.687000
> I/flutter (10384): controller.value.position:0:01:00.702000
> I/flutter (10384): controller.value.position:0:01:00.709000
> I/flutter (10384): controller.value.position:0:01:00.727000
> W/IJKMEDIA(10384): av_sync_type = AV_SYNC_VIDEO_MASTER 2
> I/flutter (10384): controller.value.position:0:01:00.754000
> I/flutter (10384): controller.value.position:0:01:00.772000
> I/flutter (10384): controller.value.position:0:01:00.787000
> I/flutter (10384): controller.value.position:0:01:00.805000
> I/flutter (10384): controller.value.position:0:01:00.821000
> I/flutter (10384): controller.value.position:0:01:00.838000
> I/flutter (10384): controller.value.position:0:01:00.854000
> I/TXCVodVideoView(10384): sendSimpleEvent 2006 play end
> W/TXCVodPlayCollection(10384): report evt 40301: token=fe84e77e-9b61-45d2-a929-d82698b7aa4c u32_timeuse=25 str_stream_url=http://1252463788.vod2.myqcloud.com/95576ef5vodtransgzp1252463788/e1ab85305285890781763144364/v.f10.mp4 u32_videotime=60 str_device_type=HLK-AL00 u32_network_type=1 str_user_id=0174304a5fc39383cd634484c5e5ba8fe733a7f3ffe1c8d318f1 str_package_name=com.jinxian.flutter_tencentplayer_example str_app_version= dev_uuid=0174304a5fc39383cd634484c5e5ba8fe733a7f3ffe1c8d318f1 u32_first_i_frame=1138 u32_isp2p=0 u32_avg_load=6851 u32_load_cnt=1 u32_max_load=6851 u32_player_type=1 u32_dns_time=131 u32_tcp_did_connect=208 u32_first_video_packet=1123 u32_server_ip=218.98.10.85
> I/flutter (10384): controller.value.position:0:01:00.698000
> ```

您好，视频源是这个 "http://aiovideo.cdn.pteplus.com.cn/encoded/mp4/ef531e34d067061895be606be7c4d35a/5de0c80cdc2df.mp4"

**Comment by iwanglian** [comment]
我也发现类似的问题， 3秒以内的视频必现。
结束之后 progress 会回退

**Comment by iwanglian** [comment]
我目前的改法是在回调时加个判断
Class TencentPlayerController 


       case 'progress':
          //只有播放时才改进度
          if(value.isPlaying)

**Comment by qq326646683** [comment]
是android里 case TXLiveConstants.PLAY_EVT_PLAY_PROGRESS:监听有问题，暂时采用上面👆修复方式。见0.12.0
