### ISSUE TITLE
[BUG]插件编译问题

### ISSUE THREAD

**Issue by jeromekai** [qq326646683/flutter_tencentplayer#63]
非 git 方式引用插件，编译阶段报错，无法找到android 里的 aar文件；git 引用也不行

**Comment by qq326646683** [comment]
@jeromekai setup for android照做了吗

**Comment by jeromekai** [comment]
是的，按照集成步骤做了

**Comment by jeromekai** [comment]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.tencent.liteav.TXCRenderAndDec found in modules classes.jar (:LiteAVSDK_Player_7.6.9376:) and classes.jar (com.tencent.liteav:LiteAVSDK_TRTC:7.8.9518)
  Duplicate class com.tencent.liteav.TXCRenderAndDec$1 found in modules classes.jar (:LiteAVSDK_Player_7.6.9376:) and classes.jar (com.tencent.liteav:LiteAVSDK_TRTC:7.8.9518)

**Comment by qq326646683** [comment]
你运行example试试，ok的话，你把build文件夹删一下，感觉是集成不同版本的插件有缓存

**Comment by jeromekai** [comment]
tencent_rtc_plugin 该插件和  tencentplayer的插件 文件重复导致的，作者有办法解决吗？

**Comment by jeromekai** [comment]
例如 Duplicate class com.tencent.liteav.basic.a.a found in modules classes.jar (:LiteAVSDK_Player_7.6.9376:) and classes.jar (com.tencent.liteav:LiteAVSDK_TRTC:7.8.9518)

**Comment by qq326646683** [comment]
两个aar里的内部冲突，这个你在官方issue里提，或者提交工单问一下

**Comment by jeromekai** [comment]
tencent_rtc_plugin该插件的作者非官方的吧，还是很感谢，~_~!
