### ISSUE TITLE
PlatformException(VideoError, Failed to load video: The operation could not be completed, null)

### ISSUE THREAD

**Issue by 2803404074** [qq326646683/flutter_tencentplayer#65]
### 5. 代码说明:
```

```

**Comment by qq326646683** [comment]
播放network的mp4或者m3u8吗

**Comment by LiGaoLiang7** [comment]
我播放的海康威视萤石云的直播地址m3u8，测试成功
但打包的时候会报错误 D:\soft\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_tencentplayer-0.12.0\android\src\main\java\com\jinxian\flutter_tencentplayer\FlutterTencentplayerPlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
出了一些乱码
