### ISSUE TITLE
非常感谢提供这么好的插件，我想请问一个问题，pod install 时候，最后提示The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/d/Desktop/tjy_news_app/ios/Pods/TXLiteAVSDK_Player/TXLiteAVSDK_Player/SDK/TXLiteAVSDK_Player.framework)，应该怎么修改呢？大佬

### ISSUE THREAD

**Issue by Etermally** [qq326646683/flutter_tencentplayer#67]
Analyzing dependencies
Downloading dependencies
Installing BSGridCollectionViewLayout (1.2.5)
Installing BSImagePicker (2.10.3)
Installing BSImageView (1.0.3)
Installing Flutter (1.0.0)
Installing TXLiteAVSDK_Player (6.8.7969)
Installing Toast (4.0.0)
Installing auto_orientation (0.0.1)
Installing flutter_forbidshot (0.0.1)
Installing flutter_tencentplayer_plus (0.0.1)
Installing flutter_webview_plugin (0.0.1)
Installing flutterautotext (0.0.1)
Installing fluttertoast (0.0.2)
Installing image_picker (0.0.1)
Installing multi_image_picker (4.7.14)
Installing path_provider (0.0.1)
Installing photo_manager (0.0.1)
Installing screen (0.0.1)
Installing shared_preferences (0.0.1)
Installing video_player (0.0.1)
Installing wakelock (0.0.1)
Installing webview_flutter (0.0.1)
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/d/Desktop/tjy_news_app/ios/Pods/TXLiteAVSDK_Player/TXLiteAVSDK_Player/SDK/TXLiteAVSDK_Player.framework)

**Comment by qq326646683** [comment]
https://www.jianshu.com/p/10a5487d8b7e
你试一下这个呢

**Comment by Etermally** [comment]
提问之前我尝试了这种办法，但是会报另外的错：
Running pod install...
Running Xcode build...
Xcode build done.                                            7.2s
Failed to build iOS app
Error output from Xcode build:
↳
Could not build the precompiled application for the device.

Error launching application on Liang的 iPhone.
2020-11-23 17:36:33.753 XCBBuildService[94335:776136] Failed to remove: /Users/d/Library/Developer/Xcode/DerivedData/Runner-hgxtiqdeubgffmgkucidqnxbpzus/Build/Intermediates.noindex/XCBuildData/8ee4f82d15aef271d1157ca010ef96e3-manifest.xcbuild: unlink(/Users/d/Library/Developer/Xcode/DerivedData/Runner-hgxtiqdeubgffmgkucidqnxbpzus/Build/Intermediates.noindex/XCBuildData/8ee4f82d15aef271d1157ca010ef96e3-manifest.xcbuild): No such file or directory (2)
2020-11-23 17:36:33.889 XCBBuildService[94335:776136] Failed to remove: /Users/d/Library/Developer/Xcode/DerivedData/Runner-hgxtiqdeubgffmgkucidqnxbpzus/Build/Intermediates.noindex/XCBuildData/8ee4f82d15aef271d1157ca010ef96e3-desc.xcbuild: unlink(/Users/d/Library/Developer/Xcode/DerivedData/Runner-hgxtiqdeubgffmgkucidqnxbpzus/Build/Intermediates.noindex/XCBuildData/8ee4f82d15aef271d1157ca010ef96e3-desc.xcbuild): No such file or directory (2)
** BUILD FAILED **


Xcode's output:
↳
warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/wakelock/libwakelock.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/webview_flutter/libwebview_flutter.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/video_player/libvideo_player.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/flutter_tencentplayer_plus/libflutter_tencentplayer_plus.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/screen/libscreen.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/shared_preferences/libshared_preferences.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/path_provider/libpath_provider.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/Runner.app/BSImagePicker.bundle' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/fluttertoast/libfluttertoast.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/photo_manager/libphoto_manager.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/flutterautotext/libflutterautotext.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/image_picker/libimage_picker.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/flutter_webview_plugin/libflutter_webview_plugin.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/Swift Compatibility Header/multi_image_picker-Swift.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/flutter_forbidshot/libflutter_forbidshot.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/libmulti_image_picker.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker-umbrella.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.modulemap' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/Project/arm64.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/auto_orientation/libauto_orientation.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/arm64-apple-ios.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/arm64-apple-ios.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/arm64.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/multi_image_picker/multi_image_picker.swiftmodule/arm64.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/Toast/libToast.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/libPods-Runner.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout-umbrella.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.modulemap' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView-umbrella.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/Project/arm64.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/arm64-apple-ios.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.modulemap' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/arm64-apple-ios.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/arm64.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/arm64.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/Swift Compatibility Header/BSGridCollectionViewLayout-Swift.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/Project/arm64.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSGridCollectionViewLayout/libBSGridCollectionViewLayout.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/arm64-apple-ios.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/arm64-apple-ios.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/arm64.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker-umbrella.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.modulemap' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/BSImageView.swiftmodule/arm64.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/Project/arm64.swiftsourceinfo' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/Swift Compatibility Header/BSImageView-Swift.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/arm64-apple-ios.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/arm64-apple-ios.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImageView/libBSImageView.a' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/arm64.swiftdoc' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/BSImagePicker.swiftmodule/arm64.swiftmodule' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/Swift Compatibility Header/BSImagePicker-Swift.h' is located outside of the allowed root paths.

warning: Stale file '/Users/d/Desktop/tjy_news_app/build/ios/Debug-iphoneos/BSImagePicker/libBSImagePicker.a' is located outside of the allowed root paths.

2 warnings generated.
40 warnings generated.
Command CompileSwift failed with a nonzero exit code
Command CompileSwift failed with a nonzero exit code
/Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_forbidshot-0.0.2/ios/Classes/FlutterForbidshotPlugin.m:77:21: warning: 'volume' is deprecated: first deprecated in iOS 7.0 - Use MPVolumeView for volume control. [-Wdeprecated-declarations]
    musicController.volume = volume.floatValue;
                    ^
In module 'MediaPlayer' imported from /Users/d/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_forbidshot-0.0.2/ios/Classes/FlutterForbidshotPlugin.m:3:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/System/Library/Frameworks/MediaPlayer.framework/Headers/MPMusicPlayerController.h:77:29: note: 'volume' has been explicitly marked deprecated here
@property (nonatomic) float volume MP_DEPRECATED("Use MPVolumeView for volume control.", ios(3.0, 7.0));
                            ^
1 warning generated.
Command CompileSwift failed with a nonzero exit code
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TXVodPlayer", referenced from:
      objc-class-ref in FLTVideoPlayer.o
  "_OBJC_CLASS_$_TXVodDownloadDataSource", referenced from:
      objc-class-ref in FLTDownLoadManager.o
  "_OBJC_CLASS_$_TXPlayerAuthParams", referenced from:
      objc-class-ref in FLTDownLoadManager.o
      objc-class-ref in FLTVideoPlayer.o
  "_OBJC_CLASS_$_TXVodPlayConfig", referenced from:
      objc-class-ref in FLTVideoPlayer.o
  "_OBJC_CLASS_$_TXVodDownloadManager", referenced from:
      objc-class-ref in FLTDownLoadManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by Etermally** [comment]
感觉好像是和其他库又冲突了😢

**Comment by qq326646683** [comment]
你还用了腾讯的其他库了吗？flutter版本多少，工程的podfile文件是和flutter版本对应吗

**Comment by Etermally** [comment]
cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6 #轮播图
  http: ^0.12.2 #网络请求
  dio: ^3.0.10 #网络请求
  flutter_webview_plugin: ^0.3.11 #webview
  webview_flutter: ^0.3.24  #webview官方提供的
  flutter_staggered_grid_view: ^0.3.2 #瀑布流组件
  fluttertoast: ^7.1.1 #toast
  flutter_easyloading: ^2.0.0 #loading
  flutterautotext:
    git: https://github.com/LiuC520/flutterautotext.git #根据给定宽度自适应缩放字体大小
  flutter_picker: ^1.1.5 #各类选择器

  flustars: ^0.3.3 #常用工具类库
  flutter_slidable: ^0.5.7 # 侧滑删除 https://pub.flutter-io.cn/packages/flutter_slidable
  # 时间格式转换 https://pub.dev/packages/date_format
  date_format: 1.0.8
  photo: ^0.4.8       #相册多图选择
  image_picker: ^0.6.7+12  #相机拍照，单图选择
  chewie: ^0.9.7
  video_player: ^0.10.1+6 #视频播放
  multi_image_picker: ^4.7.14  #相册多图选择
  lpinyin: ^1.1.0 #汉字提取拼音
  auto_orientation: ^1.0.5   #控制横竖屏控件
  screen: ^0.0.5             #控制屏幕亮度以及屏幕常亮组件
  common_utils: ^1.1.3

  flutter_forbidshot: 0.0.2
  flutter_tencentplayer_plus:
    git:
      url: https://github.com/yxwandroid/flutter_tencentplayer_plus.git


这是我使用的库

**Comment by Etermally** [comment]
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

这是flutter版本

**Comment by Etermally** [comment]
# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

这是podfile

**Comment by Etermally** [comment]
您帮忙看下 😭

**Comment by qq326646683** [comment]
你再研究一下吧，我现在没有太多时间，你运行插件里的example试试，ok的话，再找其他原因

**Comment by Etermally** [comment]
好的   我先运行一下试试吧  有问题再给您提一下  如果有空帮忙看下  谢啦
