### ISSUE TITLE
不能下载m3u8加密视频

### ISSUE THREAD

**Issue by sjoseph320** [qq326646683/flutter_tencentplayer#71]
能否支持下载m3u8加密视频

**Comment by qq326646683** [comment]
腾讯的hls加密的视频，下载后大概率播放失败

**Comment by Tencent-Alice** [comment]
您好，如果对视频加密，可以下载，但是没有秘钥无法播放。对于商业级 DRM，暂未上线，望您知悉。可参考https://cloud.tencent.com/document/product/266/45552 ， 如后续有技术问题，欢迎私信 Q2562367495，注明来意              感谢您对腾讯云的支持

**Comment by qq326646683** [comment]
经过后续和腾讯官方沟通，答案仍是二楼所说
