### ISSUE TITLE
这个库目前使用的好像是旧版的加密方案？

### ISSUE THREAD

**Issue by BadReese** [qq326646683/flutter_tencentplayer#73]
旧版加密方案文档：
https://cloud.tencent.com/document/product/266/9638#.3Ca-id.3D.22p1.22.3E.3C.2Fa.3E.E8.A7.86.E9.A2.91.E6.92.AD.E6.94.BE.E6.96.B9.E6.A1.881

新版：
https://cloud.tencent.com/document/product/266/45552

看库里面调用的是旧版的类，如
http://imgcache.qq.com/open/qcloud/video/act/liteav_android_doc/com/tencent/rtmp/TXPlayerAuthBuilder.html

现在播放加密后的视频，通过AUTH里传SIGN不管用了好像

**Comment by BadReese** [comment]
我想我理解错了，这个库不是基于超级播放器的 - -

**Comment by qq326646683** [comment]
我们用的是hls普通加密，用传token的方式，请求自己后端解密。其他方式你可以fork后发mr给我

**Comment by BadReese** [comment]
恩..不知道这个token怎么传呢？
我用的加密流程文档是这个https://cloud.tencent.com/document/product/266/46220
转码任务流是SimpleAesEncryptPreset
自适应流是
![image](https://user-images.githubusercontent.com/18170860/105580565-0a256f80-5dc8-11eb-8290-8ea0b396ee16.png)

应该也是HLS吧？
麻烦有空帮我看看，谢谢~

**Comment by qq326646683** [comment]
hls加密是我们后端做的，我就负责传token解密播放，文档里有加token的说明

**Comment by qq326646683** [comment]
就是headers参数
