### ISSUE TITLE
倍速播放支持慢速吗，比如0.5X

### ISSUE THREAD

**Issue by judastatus** [qq326646683/flutter_tencentplayer#75]
### 1. 设备/系统版本:
0.13.0版本
### 2. bug描述:
在视频播放时，倍速播放支持0.5倍速吗
### 5. 代码说明:
```

```

**Comment by qq326646683** [comment]
我记得可以，你试一试就知道了

**Comment by judastatus** [comment]
我设置了倍速0.5， 然后将 setRate里原来小于1.0的判断注释掉，在切换0.5倍播放的时候会闪退。
![image](https://user-images.githubusercontent.com/15098424/105651927-1fe38380-5ef3-11eb-8695-d46f46b7f429.png)

**Comment by qq326646683** [comment]
闪退日志 看下呢

**Comment by qq326646683** [comment]
android没问题，ios有内存问题

**Comment by judastatus** [comment]
> android没问题，ios有内存问题

我昨天是在一直在iOS上试的，那iOS内存这个有解决办法吗？

**Comment by qq326646683** [comment]
这个一时半会解决不了

**Comment by judastatus** [comment]
> 这个一时半会解决不了

ok,好的
