### ISSUE TITLE
【ios】ios列表播放只能初始化一个 tencentPlayerController  并且是空白不显示缩略图

### ISSUE THREAD

**Issue by erfu25** [qq326646683/flutter_tencentplayer#76]
### 2. bug描述:ios列表播放只能初始化一个 tencentPlayerController  并且是空白不显示缩略图 
安卓都能初始化

### 5. 代码说明:
```

```

插件是否支持显示缩略图？使用的是腾讯云点播视频源

![1611644511118](https://user-images.githubusercontent.com/38412032/105811418-9366bd00-5fe7-11eb-96d2-5b3fe6c4e789.jpg)

**Comment by erfu25** [comment]
![1611644511118](https://user-images.githubusercontent.com/38412032/105811500-b5f8d600-5fe7-11eb-83e1-60110aa2a622.jpg)

**Comment by erfu25** [comment]
安卓我又试了一下 使用腾讯云点播视频源 无法初始化 插件版本0.11.0

**Comment by qq326646683** [comment]
显示部分，没有初始化完成用展位图呗，偏业务了

**Comment by qq326646683** [comment]
android你试试demo行不行，没听说过不能

**Comment by erfu25** [comment]
> 显示部分，没有初始化完成用展位图呗，偏业务了
安卓是可以列表全都初始化完成的 ios不行只能初始化一个 不是没有初始化完的意思哦

**Comment by erfu25** [comment]
> android你试试demo行不行，没听说过不能

是的是的安卓是可以的 但是安卓使用腾讯云点播资源（appid fileid）  也是没法初始化成功的

**Comment by qq326646683** [comment]
demo里有抖音视频列表的例子，你看看

**Comment by qq326646683** [comment]
看日志，分析一下为啥不成功

**Comment by erfu25** [comment]
> 看日志，分析一下为啥不成功
感谢🙏
安卓的找到了 是因为appid要number类型的  demo我晚上回去跑跑看
