### ISSUE TITLE
startTime未按照预期执行

### ISSUE THREAD

**Issue by Mockingbird1234** [qq326646683/flutter_tencentplayer#81]
### 1. 设备/系统版本:
安卓/ios
### 2. bug描述:
在播放网络资源时，设置自动播放，刚开始（前2s内）加载资源时获取到的总时间是不准确的，这样就会出现一个问题，比如播放2700秒的资源，刚加载资源时获取的总时间可能也就7、8秒，然后startTime设置1800秒，最终并不会从1800秒开始播放。
### 3. 实际结果:
从头开始播放
### 4. 预期结果:
从指定的秒数开始播放
### 5. 代码说明:
```
controller = TencentPlayerController.network(
          dataSource,
          playerConfig: PlayerConfig(
              autoPlay:true
              headers: headers,
              startTime: 1800,
              ),
        )..initialize();
```

**Comment by qq326646683** [comment]
什么资源，总时长会错？

**Comment by Mockingbird1234** [comment]
不好意思，我没有说清楚，就是m3u8资源，比如https://sina.com-h-sina.com/20180811/7885_8d758bc7/index.m3u8，初始化后的前几秒获取到的总时长是不对的，过上几秒钟之后总时长是对的。这样就会造成starttime参数不生效。

**Comment by qq326646683** [comment]
新浪的源，腾讯播放器可能支持的不好

**Comment by Mockingbird1234** [comment]
好的，谢谢解答。
