### ISSUE TITLE
[feature] 对加密视频播放

### ISSUE THREAD

**Issue by YeFei572** [qq326646683/flutter_tencentplayer#84]
请问现在播放器是否支持hls/m3u8的aes-128解密方式进行播放，无需下载，播放即可，我看源码好像加密只是token方式加密，不知道有没有看漏

**Comment by qq326646683** [comment]
我们应用的是腾讯hls加密，视频加密的片段里有请求解密的url（自己app后端实现），我们客户端传headers信息进行解密

**Comment by YeFei572** [comment]
我在别的issue看到你这样回答的了， 腾讯自己的确实可以这样，但是市面上大多数据加密不是这种加token的加密方式， 因为市面上大多数的加密都是采用AES-128加密，他们每一个切片都会加密，所以我想咱们能不能支持一下？

**Comment by qq326646683** [comment]
HLS 普通加密方案

加密算法
云点播系统目前支持 HLS 中规定的加密方案（HLS 普通 AES 加密技术），使用 AES-128 对视频内容本身进行加密。
