### ISSUE TITLE
请问一下播放器支持配置签名吗

### ISSUE THREAD

**Issue by JarynChen** [qq326646683/flutter_tencentplayer#86]
腾讯云云点播的播放器支持配置签名，请问下这个插件支持携带签名吗

https://cloud.tencent.com/document/product/266/45552

**Comment by qq326646683** [comment]
![image](https://user-images.githubusercontent.com/15717688/107178973-471c7380-6a10-11eb-96b9-17312119feb4.png)
我们只做了HLS 普通加密，其他的需要你自己去做了

**Comment by qq326646683** [comment]
@JarynChen 我加上了，还没发布到pub，可以切到下面测试下，OK的话我再发布。
```
flutter_easemob_kefu:
    git:
      url: https://github.com/qq326646683/flutter_tencentplayer.git
```

**Comment by JarynChen** [comment]
> @JarynChen 我加上了，还没发布到pub，可以切到下面测试下，OK的话我再发布。
> 
> ```
> flutter_tencentplayer:
>     git:
>       url: https://github.com/qq326646683/flutter_tencentplayer.git
> ```

谢谢，我尝试一下，新年快乐！

**Comment by qq326646683** [comment]
@JarynChen 这个能用吗
