### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by queyaliang** [qq326646683/flutter_tencentplayer#87]
### 1. 设备/系统版本:
Android  ： 5.1.1 
### 2. bug描述:
引用：  flutter_tencentplayer: ^0.13.0

a. 按照官方切换源方法，在切换播放源后，发现内存不断增加，
if (_controller != null) {
      _controller.removeListener(_videoListener);
      _controller.pause();}
b. 更换成
if (_controller != null) {
      _controller.removeListener(_videoListener);
      _controller.pause();
      _controller.dispose();
      _controller = null;
    }
  切换源后，内存不会再增加，但是每次切源后界面都会出现一个异常，然后过1s左右界面播放切换后得源
### 3. 实际结果:
a. 内存不断增加
b.界面必现 A TencentPlayerController was used after being disposed. 

  Container file:///C:/workspace/other/flutter_app/lib/TencentVideo.dart:56:14

这种异常提示，但是，在带哦用dispose方法后，就没有再次调用controller，并且报错得地方，就在 state 得build 方法下，里面没有相关controller 处理
 @override
  Widget build(BuildContext context) {
    print('HomeVideo2 ==> build ==> start ');
    if(_controller == null){
      print('HomeVideo2 ==> build ==> start 1 ');

      return Container( decoration: BoxDecoration(   // 《--- 此处是56行
        color: Colors.blue,
        borderRadius: BorderRadius.circular(5),

### 4. 预期结果:
  a.切源后，内存不会泄露，
  b.dispose后，界面不会出现异常 

### 5. 代码说明:
```

```

**Comment by queyaliang** [comment]
已查找到，泄露位置，
官方example中的AutoChangeNextSourcePage，测试后，也发现内存泄漏
检查后，原因在于 
controller != null
              ? controller.value.initialized
                  ? AspectRatio(
                      aspectRatio: controller.value.aspectRatio,
                      child: TencentPlayer(controller),
                    )
                  : Image.asset('static/place_nodata.png')
              : Container(
                  child: Text('loading ... '),
                )
前面加入了：controller != null
              ? controller.value.initialized
                  ? 
这两个判断，移除后，直接放入
AspectRatio(
                      aspectRatio: controller.value.aspectRatio,
                      child: TencentPlayer(controller),
                    )
不会导致内存泄漏
希望官方解释处理一下
谢谢！

**Comment by qq326646683** [comment]
<img width="506" alt="flutterperformance" src="https://user-images.githubusercontent.com/15717688/113651888-67da1000-96c5-11eb-9de8-3b23551397d8.png">

**Comment by qq326646683** [comment]
用demo里自动切换集测试，内存稳定60m左右
