### ISSUE TITLE
不支持音量修改吗

### ISSUE THREAD

**Issue by SpringerInFighting** [qq326646683/flutter_tencentplayer#9]

**Comment by qq326646683** [comment]
音量我放到另外一个插件里了：
https://github.com/qq326646683/flutter_forbidshot/blob/master/lib/flutter_forbidshot.dart#L42-L44

**Comment by SpringerInFighting** [comment]
你这个音量插件是直接修改系统音量的吧，我想要的效果是可以控制视频是否静音，而又不影响系统音量，这个需要配合你那个视频插件实现的吧，谢谢了
&nbsp;




庞卓健
天天五折


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qq326646683"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 晚上6:11
收件人: "qq326646683/flutter_tencentplayer"<flutter_tencentplayer@noreply.github.com&gt;; 
抄送: "难断"<1538563097@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qq326646683/flutter_tencentplayer] 不支持音量修改吗 (#9)




音量我放到另外一个插件里了：
 https://github.com/qq326646683/flutter_forbidshot/blob/master/lib/flutter_forbidshot.dart#L42-L44

**Comment by qq326646683** [comment]
腾讯播放器sdk里没有调节音量的api

**Comment by SpringerInFighting** [comment]
好吧，谢谢&nbsp;




庞卓健
天天五折


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qq326646683"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 上午10:44
收件人: "qq326646683/flutter_tencentplayer"<flutter_tencentplayer@noreply.github.com&gt;; 
抄送: "难断"<1538563097@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qq326646683/flutter_tencentplayer] 不支持音量修改吗 (#9)




腾讯播放器sdk里没有调节音量的api
