### ISSUE TITLE
直播的sdk有吗

### ISSUE THREAD

**Issue by 673697831** [qq326646683/flutter_tencentplayer#92]
有对TXLivePlayer进行的封装吗

**Comment by qq326646683** [comment]
只封装了TXVodPlayer，也可以播放直播

**Comment by 673697831** [comment]
我这边不支持直播，好像直播不是所有格式都可以
http://liteavapp.qcloud.com/live/liteavdemoplayerstreamid_demo1080p.flv

**Comment by qq326646683** [comment]
![681617701822_ pic_hd](https://user-images.githubusercontent.com/15717688/113691230-cbccfa80-96fe-11eb-8950-837e1fa5bb78.jpg)
可以啊，我用你链接播放出来了

**Comment by 673697831** [comment]
flutter 用TXLivePlayer 播放，只能播放hls的
 https://pub.dev/packages/ftl_player

**Comment by 673697831** [comment]
安卓上是这样，iOS可以
