### ISSUE TITLE
是不是有些视频格式不支持倍速播放

### ISSUE THREAD

**Issue by Wiki1991** [qq326646683/flutter_tencentplayer#93]
相机拍摄的可以倍速播放，录屏的视频无法倍速

**Comment by qq326646683** [comment]
是腾讯云的视频吗？其他视频没有试过，也许腾讯播放器sdk支持的不稳定

**Comment by Wiki1991** [comment]
> 是腾讯云的视频吗？其他视频没有试过，也许腾讯播放器sdk支持的不稳定

不是腾讯云，上传到阿里oss的视频

**Comment by Wiki1991** [comment]
> > 是腾讯云的视频吗？其他视频没有试过，也许腾讯播放器sdk支持的不稳定
> 
> 不是腾讯云，上传到阿里oss的视频

解决了，我在上传视频文件之前用ffmpeg给视频转码增加了一个帧数
`
 final String looselessConversion = '-r 1 -i $path -r 24 $pathCopy';
final int returnCode = await _flutterFFmpeg.execute(looselessConversion);
`
