### ISSUE TITLE
下载的视频格式是m3u8.sqlite，还需要联网才能播放？

### ISSUE THREAD

**Issue by Mockingbird1234** [qq326646683/flutter_tencentplayer#95]
### 1. 设备/系统版本:
安卓/ios
### 2. bug描述:
使用下载功能下载了一个未加密的m3u8文件，下载后发现是m3u8.sqlite，使用file方式播放时，发现需要联网才能看。
### 3. 实际结果:
联网才能播放
### 4. 预期结果:
断网可以播放
### 5. 代码说明:
```
 if (urlOrFileId.startsWith("http")) {
                txVodDownloadMediaInfo = downloader.startDownloadUrl(urlOrFileId);
            } else {
                TXPlayerAuthBuilder auth = new TXPlayerAuthBuilder();
                auth.setAppId(((Number)call.argument("appId")).intValue());
                auth.setFileId(urlOrFileId);
                int quanlity = ((Number)call.argument("quanlity")).intValue();
                String templateName = "HLS-标清-SD";
                if (quanlity == 2) {
                    templateName = "HLS-标清-SD";
                } else if (quanlity == 3) {
                    templateName = "HLS-高清-HD";
                } else if (quanlity == 4) {
                    templateName = "HLS-全高清-FHD";
                }
                TXVodDownloadDataSource source = new TXVodDownloadDataSource(auth, templateName);
                txVodDownloadMediaInfo = downloader.startDownload(source);
            }
```

**Comment by qq326646683** [comment]
我记得不需要联网

**Comment by Mockingbird1234** [comment]
> 我记得不需要联网

文件确实已经下载下来了，格式是***.m3u8.sqlite，我播放file文件联网可以播放，断了网之后就不行了，请问有什么解决方法吗？

**Comment by qq326646683** [comment]
我用example测试，android和ios均可在断网后播放下载好的视频。你这个视频是做加密了吗？

**Comment by Mockingbird1234** [comment]
应该是没有加密，可以帮忙测试下这个m3u8吗？ 谢谢

https://cache.parwix.com:4433/cache/iqiyi/eadd9f38a5843256ea29aec63b798b87.m3u8

**Comment by qq326646683** [comment]
腾讯播放器报的
```
-[TXCVodPlayer onPlayer:event:params:] -2305, {
    "EVT_MSG" = "HLS Decrypt key";
```
应该是你这流片段里有HLS加密相关的，断网后无法请求解密了

**Comment by qq326646683** [comment]
经多次和腾讯沟通和验证，加密视频是不支持下载后播放的

**Comment by Mockingbird1234** [comment]
好的，谢谢回复，我使用m3u8下载器下载这个地址转换成mp4格式可以正常播放，是不是能证明这个地址没有被加密？
![image](https://user-images.githubusercontent.com/18496728/116497934-2232f080-a8db-11eb-967f-97fbd1e2eb6a.png)

![image](https://user-images.githubusercontent.com/18496728/116497966-337bfd00-a8db-11eb-924b-776f31123f11.png)

**Comment by qq326646683** [comment]
![image](https://user-images.githubusercontent.com/15717688/116528355-52e04d80-a90e-11eb-964a-02bba5679c32.png)
应该是爱奇艺的资源腾讯播放器支持的不好
