### ISSUE TITLE
播放rtmp地址，流直播的视频画面 横竖屏切换之后，播放器播放的画面比例异常。

### ISSUE THREAD

**Issue by lan2000** [qq326646683/flutter_tencentplayer#96]
### 1. 设备/系统版本:
安卓10 ，运行demo，SDKVersion = 2 , 8.2.9809  

### 2. bug描述:
播放rtmp地址，流直播的视频画面 横竖屏切换之后，播放器播放的画面比例异常。
播放器比例是根据controller.value.aspectRatio来设置，但是打印日志查看返回的信息，TencentPlayerValue的size没有变化。
进一步测试，推流的时候修改分辨率，播放器这边打印的日志获取TencentPlayerValue的size没有改变。退出播放器，再次进入播放页面则获取正确size。

### 5. 代码说明:
```
在controller.addListener(listener);
listener里面获取controller.value.size
```

**Comment by lan2000** [comment]
大佬，点播播放器TXVodPlayer播放这个rtmp是没有监听后面分辨率的变化。什么时候也能把TXLivePlayer也弄进去！

**Comment by qq326646683** [comment]
你的意思是vodplayer的问题吗，目前没有用liveplayer的场景和计划
