### ISSUE TITLE
插件代码空指针闪退

### ISSUE THREAD

**Issue by bobulucky** [qq326646683/flutter_tencentplayer#98]
更新flutter版本到2.0.5后插件版本升级到0.15.0，gradle版本更新到gradle-6.5-all，打开视频就是闪退，看日志是插件代码空指针问题。

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.56.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

load library txffmpeg from system path 
W/Native-LiteAV(32609): load library txffmpeg true
W/Native-LiteAV(32609): load library traeimp-rtmp from system path 
W/Native-LiteAV(32609): load library : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.flutterwupaomall-WCtZEfKc1HpRWWD37eDXkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.flutterwupaomall-WCtZEfKc1HpRWWD37eDXkQ==/lib/arm64, /data/app/com.xxx.flutterwupaomall-WCtZEfKc1HpRWWD37eDXkQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libtraeimp-rtmp.so"
W/Native-LiteAV(32609): load library traeimp-rtmp false
W/Native-LiteAV(32609): load library liteavsdk from system path 
W/JNI_UTIL(32609): JniHelper::setJavaVM(0x7bc8b01e40), thread = 533909767520
I/JNI_UTIL(32609): JniHelper::cacheEnv when no cache in thread = 533909767520
D/JNI_UTIL(32609): JniHelper::GetEnv JNI_OK cache env 0x7bc8a46400
I/Native-LiteAV(32609):  ################ liteavsdk 8.2.9809 arm64 ############### 
W/Native-LiteAV(32609): load library liteavsdk true
I/flutter (32609): videoDetail => 加载内容页面
I/TXCLog  (32609): TXCLog init log file path : /storage/emulated/0/Android/data/com.xxxx.flutterwupaomall/files/log/tencent/liteav, cache : /data/user/0/com.xxx.flutterwupaomall/files/log/tencent/liteav
W/Unknow  (32609): ^^^^^^^^^^Dec 26 2020^^^01:01:11^^^^^^^^^^[32609,32609][2021-05-07 +0800 18:35:47]
W/Unknow  (32609): del time out files time: 1
W/Unknow  (32609): get mmap time: 0
W/Unknow  (32609): SDK_VERSION: 8.2.9809
W/Unknow  (32609): SDK_ID: 2
W/Unknow  (32609): log appender mode:0, use mmap:1
I/TXVodPlayer(32609): setLoop:false
I/TXVodPlayer(32609): setAutoPlay:true
I/TXVodPlayer(32609): setSurface Surface:Surface(name=android.graphics.SurfaceTexture@e2800eb)/@0x8122e48
E/MethodChannel#flutter_tencentplayer(32609): Failed to handle method call
E/MethodChannel#flutter_tencentplayer(32609): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/MethodChannel#flutter_tencentplayer(32609): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.setPlaySource(FlutterTencentplayerPlugin.java:167)
E/MethodChannel#flutter_tencentplayer(32609): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin$TencentPlayer.<init>(FlutterTencentplayerPlugin.java:84)
E/MethodChannel#flutter_tencentplayer(32609): 	at com.jinxian.flutter_tencentplayer.FlutterTencentplayerPlugin.onMethodCall(FlutterTencentplayerPlugin.java:474)
E/MethodChannel#flutter_tencentplayer(32609): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_tencentplayer(32609): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_tencentplayer(32609): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_tencentplayer(32609): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_tencentplayer(32609): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_tencentplayer(32609): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#flutter_tencentplayer(32609): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/MethodChannel#flutter_tencentplayer(32609): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_tencentplayer(32609): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#flutter_tencentplayer(32609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/DartMessenger(32609): Uncaught exception in binary message listener
E/DartMessenger(32609): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(32609): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/DartMessenger(32609): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger(32609): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(32609): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DartMessenger(32609): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(32609): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/DartMessenger(32609): 	at android.os.Looper.loop(Looper.java:181)
E/DartMessenger(32609): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/DartMessenger(32609): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(32609): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/DartMessenger(32609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by qq326646683** [comment]
sign非必传字段忘记判空了，0.16.0已修复

**Comment by bobulucky** [comment]
0.16.0已经正常运行
