### ISSUE TITLE
0.16.0Android真机调试正常，打包播放闪退

### ISSUE THREAD

**Issue by bobulucky** [qq326646683/flutter_tencentplayer#99]
app/build.gradle
android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
//        checkReleaseBuilds false
//        abortOnError false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xxx.flutterwupaomall"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            ndk {
                abiFilters 'armeabi-v7a'
            }
            // minifyEnabled true
            // useProguard true

            // proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

闪退日志：
F/crashpad(12882): dlopen: dlopen failed: library "libandroidicu.so" not found: needed by /system/lib64/libharfbuzz_ng.so in namespace (default)
F/libc    (12556): Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x1 in tid 12881 (ff_read), pid 12556 (lutterwupaomall)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/umi/umi:11/RKQ1.200826.002/V12.5.3.0.RJBCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-05-08 18:11:58+0800
pid: 12556, tid: 12881, name: ff_read  >>> com.xxx.flutterwupaomall <<<
uid: 10399
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x1
    x0  b4000074298e5800  x1  0000000000000001  x2  0000007410b5c870  x3  0000000000001018
    x4  0000000000000001  x5  8080800000000000  x6  fefeff731d0ac29f  x7  7f7f7f7f7f7fffff
    x8  0101010101010101  x9  c70618b1600e6ab2  x10 00000074211ebe20  x11 b40000743612c4a0
    x12 0000000000000008  x13 0000000000000000  x14 0000000000000080  x15 0000000008000000
    x16 000000741e0e9e48  x17 0000007566155330  x18 000000740faf6000  x19 000000741e0eb000
    x20 0000007410b5c870  x21 b4000074298e5800  x22 b400007436152b78  x23 b400007436152b20
    x24 0000000000000000  x25 0000007410b5db48  x26 000000741d729000  x27 0000000000000001
    x28 0000007410a65000  x29 0000007410b5da50
    lr  000000741deba484  sp  0000007410b5c830  pc  0000000000000001  pst 0000000000001000
backtrace:
      #00 pc 0000000000000001  <unknown>
      #01 pc 000000000020f480  /data/app/~~lyKD5Qwv-PXXjCe9pvq5hg==/com.xxx.flutterwupaomall-TcngBKThCL6Im_b3532zmA==/lib/arm64/libtxffmpeg.so (av_application_on_http_event+24)
Lost connection to device.

ios 9.0仅仅只设置需要支持http协议才能正常运行

**Comment by qq326646683** [comment]
ios 9.0仅仅只设置需要支持http协议才能正常运行
这样就可以了吗

**Comment by qq326646683** [comment]
flutter build apk --release --no-shrink
有用这个命令打包？

**Comment by qq326646683** [comment]
@bobulucky

**Comment by bobulucky** [comment]
@qq326646683 问题找到了，打包混淆的问题。按照示例demo的配置然后flutter build apk --release --no-shrink我这边也是有问题的。最后我的解决方法是查找了腾讯播放器官方文档添加上了混淆规则，我贴一下配置代码。
android/app/proguard-rules.pro
-keep class com.tencent.** { *; }

android/app/build.gradle
release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            ndk {
                abiFilters 'armeabi-v7a'
            }
            shrinkResources true
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
 
关于ios的按照readme要求info.plist配置：
<key>NSAllowsArbitraryLoads</key>
		<true/>
这个在打包运行是会有http的一个不支持提示，我这边有自己配置了一下可以运行
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>playvideo.qcloud.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequirestForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<true/>
			</dict>
		</dict>
	</dict>
到目前为止我遇到的问题是由以上两个配置文件解决运行正常，如果有类似问题这些配置大家可以参考
